### ISSUE TITLE
Incorrect test error message when test failed. 

### ISSUE THREAD

**Issue by EduardTrutsyk** [it-shark-pro/js-assignments#5]
We need to update our test and swap actual and expected results.

![image](https://user-images.githubusercontent.com/5457280/36775501-5d746040-1c73-11e8-8a6f-eed26b19d2f5.png)

Documentation: https://nodejs.org/api/assert.html#assert_assert_equal_actual_expected_message
Current implementation: 
`assert.equal(5, getAverage(5, 5));` 
should be:
`assert.equal(getAverage(5, 5), 5);`

We need to update ALL out tests.

Thank you @OlgaVoronko for the report :+1:

**Comment by AliakseiBychyk** [comment]
The assertions were corrected, PR#7 is open.

**Comment by EduardTrutsyk** [comment]
done #7
